	-- Exploratory Data Analysis --
	/* DATA EXPLORATION */

		-- EXPLORE ALL Objects In Database
		SELECT * FROM INFORMATION_SCHEMA.TABLES

		-- EXPLORE ALL COLUMNS IN THE DATABASE
		SELECT * FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'dim_customers'
