-- Exploratory Data Analysis --
/* MAGNITUDE Analysis */ -- ( Sort the data by Measure )--


-- Find the total customers by countries
SELECT 
        country,
        COUNT(customer_key) As Total_customers
        FROM gold.dim_customers
        GROUP BY country
ORDER BY Total_customers DESC;
-- Find total customers by gender
SELECT 
        gender,
        COUNT(customer_key) As Total_customers
        FROM gold.dim_customers
        GROUP BY gender
ORDER BY Total_customers DESC;
-- Find total products by category
SELECT 
        category, 
        COUNT(product_key) As Total_products 
        FROM gold.dim_products
        GROUP BY category
ORDER BY Total_products DESC;
-- What is the average costs in each category ??
SELECT 
        category,
        AVG(cost) As Avg_cost 
        FROM gold.dim_products
        GROUP BY category
ORDER BY Avg_cost DESC;  
-- What is the total revenue generated for each product category ??
SELECT 
        p.category,
        SUM(sales_amount) As Total_revenue 
        FROM gold.fact_sales f
        LEFT JOIN gold.dim_products p
        ON f.product_key = p.product_key
        GROUP BY p.category
ORDER BY Total_revenue DESC;
-- Find the total revenue generated by each customers
SELECT 
        c.customer_key,
        c.first_name,
        c.last_name,
        SUM(f.sales_amount) As Total_revenue_by_customer 
        FROM gold.fact_sales f
        LEFT JOIN gold.dim_customers c
        ON f.customer_id = c.customer_id
        GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY  Total_revenue_by_customer DESC;
-- What is the distribution of sold items across countries ?
SELECT 
            c.country,
            SUM(f.quantity) AS total_items_sold
        FROM gold.fact_sales f
        LEFT JOIN gold.dim_customers c
        ON f.customer_id = c.customer_id
        GROUP BY c.country
ORDER BY total_items_sold DESC;